### ISSUE TITLE
Unable to load extension

### ISSUE THREAD

**Issue by ghecko** [giggi0x00/Sigrok_TPM_SPI_Extractor#1]
I got this error when I tried to load the decoder (list supported decoder with `sigrok-cli -L`) after copying files in the decoders/tpm_key_sniffing folder:

`srd: AttributeError: Failed to load decoder tpm_key_sniffing: no 'Decoder' attribute in imported module: module 'tpm_key_sniffing' has no attribute 'Decoder'`

I use the sigrok-cli version 0.7.1.

Do you have any information about this ?

I've also tried to rename tpm_key_sniffing.py to pd.py as recommend by sigrok in their docs

**Comment by ghecko** [comment]
The issue can be solved by simply renaming the "_init__.py" file to "__init__.py" (typo in file name)

**Comment by giggi0x00** [comment]
Thanks Jordan.
